name: Publish Eslint Config to npmjs

on:
  push:
    branches:
      - 'release/eslint-config/**'
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm -F eslint-config i

      - name: Build eslint-config
        run: pnpm -F eslint-config build

      - name: Publish eslint-config
        run: pnpm -F eslint-config publish --no-git-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
