name: Publish Logger to npmjs

on:
  push:
    branches:
      - 'release/logger/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          node-version: '20.x'
      - run: pnpm logger i
      - run: pnpm logger build
      - run: pnpm logger publish --no-git-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
