name: Publish Packages to npm

on:
  push:
    branches:
      - 'release/**'

jobs:
  publish-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - logger

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8

      - name: Set package variable
        id: set_package
        run: echo "PACKAGE=$(echo ${GITHUB_REF#refs/heads/release/} | cut -d'/' -f1)" >> $GITHUB_ENV

      - name: Install specific package dependencies
        run: pnpm -F ${{ env.PACKAGE }} i

      - name: Build specific package
        run: pnpm -F ${{ env.PACKAGE }} build

      - name: Publish specific package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm -F ${{ env.PACKAGE }} publish --no-git-checks
